-- Social Engineering Simulator - Database Schema & Initial Data

-- 1. Create Users Table
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

-- 2. Create Results Table
DROP TABLE IF EXISTS Results;
CREATE TABLE Results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    score INTEGER NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

-- 3. Creat Scenarios Table
 CREATE TABLE Scenarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    option1 TEXT NOT NULL,
    option2 TEXT NOT NULL,
    option3 TEXT NOT NULL,
    option4 TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    explanation TEXT NOT NULL,
    warning_indicators TEXT NOT NULL,
    
    title_en TEXT NOT NULL,
    category_en TEXT NOT NULL,
    description_en TEXT NOT NULL,
    option1_en TEXT NOT NULL,
    option2_en TEXT NOT NULL,
    option3_en TEXT NOT NULL,
    option4_en TEXT NOT NULL,
    explanation_en TEXT NOT NULL,
    warning_indicators_en TEXT NOT NULL
);

-- 4. INSERT INTO Scenarios (
    title, category, description, option1, option2, option3, option4, correct_answer, explanation, warning_indicators,
    title_en, category_en, description_en, option1_en, option2_en, option3_en, option4_en, explanation_en, warning_indicators_en
) VALUES 
(
    'تحديث الحساب البنكي', 'Phishing Email', 
    'وصلتك رسالة بريدية من بنكك تطلب تحديث بياناتك فوراً عبر رابط خارجي لتجنب إغلاق الحساب.', 
    'النقر على الرابط وتحديث البيانات فوراً لتفادي تجميد الحساب.', 
    'إعادة إرسال الرسالة إلى بريد الدعم الفني للبنك للتحقق من صحتها.', 
    'تجاهل الرسالة والتواصل مع البنك مباشرة عبر أرقام خدمة العملاء الرسمية.', 
    'فتح الرابط من متصفح خفي (Incognito) لتسجيل الدخول بأمان.', 
    'Option 3', 
    'البنوك لا تطلب إطلاقاً تحديث البيانات الحساسة عبر روابط في البريد الإلكتروني.', 
    'رابط خارجي مشبوه • لغة الاستعجال والتهديد • طلب بيانات حساسة عبر البريد',
    'Bank Account Update', 'Phishing Email', 
    'You received an email from your bank asking to immediately update your account details via an external link to prevent account suspension.', 
    'Click the link and update your data immediately to avoid freeze.', 
    'Forward the email to the bank support to verify its authenticity.', 
    'Ignore the message and contact the bank directly via official phone numbers.', 
    'Open the link in Incognito mode to log in securely.', 
    'Banks never request sensitive updates via email links.', 
    'Suspicious external link • Urgent/Threatening tone • Requesting credentials via email'
),
(
    'فاتورة غير مدفوعة', 'Phishing Email', 
    'تلقيت بريداً يحتوي على ملف مرفق باسم Invoice_September.pdf.exe يُطلب منك فتحه لمراجعة التكاليف.', 
    'عدم فتح المرفق وحذف الرسالة فوراً لأن الامتداد الحقيقي هو exe وليس pdf.', 
    'تنزيل الملف وفحصه باستخدام برنامج الحماية (Antivirus) قبل فتحه.', 
    'فتح الملف لرؤية تفاصيل الفاتورة ثم التواصل مع المرسل للاستفسار.', 
    'حفظ الملف على Google Drive وفتحه من هناك لتفادي الفيروسات.', 
    'Option 1', 
    'خدعة الامتداد المزدوج (pdf.exe) تُستخدم لإخفاء البرمجيات الخبيثة.', 
    'امتداد مزدوج خبيث (.exe) • مرفق بريدي غير متوقع • ضغط لتسديد فاتورة',
    'Unpaid Invoice', 'Phishing Email', 
    'You received an email with an attachment named Invoice_September.pdf.exe asking you to open it to review costs.', 
    'Do not open the attachment and delete the email immediately because the real extension is exe.', 
    'Download the file and scan it with antivirus before opening.', 
    'Open the file to see invoice details then contact the sender.', 
    'Save the file to Google Drive and open it there to avoid viruses.', 
    'Double extension trick (pdf.exe) is used to hide malicious executables.', 
    'Executable double extension (.exe) • Unexpected attachment • Payment urgency'
),
(
    'الفوز بجائزة', 'Phishing Email', 
    'رسالة تهنئة بفوزك بسحب عشوائي تطلب منك دفع رسوم الشحن عبر بطاقتك الائتمانية.', 
    'تزويدهم ببيانات بطاقة مسبقة الدفع (Prepaid) بها مبلغ بسيط فقط.', 
    'مراسلة المرسل لطلب خصم رسوم الشحن من قيمة الجائزة الكلية.', 
    'إدخال بيانات البطاقة البنكية الأساسية للتعجيل باستلام الجائزة.', 
    'تجاهل الرسالة تماماً وحظر المرسل لأن المسابقة احتيالية.', 
    'Option 4', 
    'المسابقات الوهمية تهدف لسحب بيانات البطاقات البنكية تماماً.', 
    'طلب بيانات بطاقة ائتمانية • الوعود بفرص فوز خيالية • رسوم شحن مجهولة المصدر',
    'Prize Lottery Winner', 'Phishing Email', 
    'A congratulatory email claims you won a raffle and asks for shipping fees via your credit card.', 
    'Provide a prepaid card with a small balance.', 
    'Contact sender to deduct shipping from the prize total.', 
    'Enter main credit card details to expedite delivery.', 
    'Ignore the message and block sender as it is fraudulent.', 
    'Fake lotteries strictly aim to collect and steal credit card data.', 
    'Credit card credentials request • Unrealistic reward promises • Unknown shipping fee'
),
(
    'تغيير كلمة المرور', 'Phishing Email', 
    'تنبيه أمني يدعي حدوث اختراق لحسابك ويحتوي على رابط سريع لتغيير كلمة المرور.', 
    'الضغط على الرابط وتغيير كلمة السر فوراً لحماية الحساب.', 
    'التحقق من عنوان بريد المرسل (Domain) ثم الانتقال للموقع الرسمي بشكل مستقل وتغيير كلمة السر.', 
    'إدخال كلمة مرور وهمية في الرابط المرفق للتأكد من مصداقية الموقع.', 
    'تجاهل الرسالة كلياً وعدم تغيير كلمة المرور في أي مكان.', 
    'Option 2', 
    'يجب دائماً التحقق من عنوان المرسل وتغيير كلمة المرور عبر الدخول للموقع الرسمي مباشرة.', 
    'نطاق مرسل غير موثوق • إيقاد الخوف والاستعجال • زر مباشر لإعادة الضبط',
    'Password Reset Security Alert', 'Phishing Email', 
    'A security alert claims your account was breached and offers a quick link to reset your password.', 
    'Click the link and change password immediately.', 
    'Verify sender domain, then independently navigate to official site to change password.', 
    'Enter a fake password in the link to test credibility.', 
    'Ignore message completely without resetting.', 
    'Always verify the sender domain and reset passwords directly via official portals.', 
    'Untrusted sender domain • Fear/Urgency exploitation • Direct reset button link'
),
(
    'استبيان بمكافأة', 'Phishing Email', 
    'دعوة لتعبئة استبيان مقابل مبلغ مالي تطلب منك تسجيل الدخول بحسابك الجامعي لتأكيد هويتك.', 
    'تسجيل الدخول بالحساب الجامعي للحصول على المكافأة المادية.', 
    'تعبئة الاستبيان ببيانات شخصية وهمية لتجنب سرقة الهوية.', 
    'إغلاق الصفحة والتبليغ عن البريد لأن طلب تسجيل الدخول لا يتوافق مع الاستبيانات العامة.', 
    'مشاركة رابط الاستبيان مع زملائك لتأكيد إذا كان يعمل معهم.', 
    'Option 3', 
    'طلبات تسجيل الدخول في الاستبيانات الخارجية هي مصيدة لجمع بيانات الحسابات الجامعية.', 
    'طلب اعتماد الحساب الجامعي • إغراء المبالغ المالية • استبيان خارجي مجهول',
    'Paid Survey Offer', 'Phishing Email', 
    'An invitation to complete a paid survey asks you to log in with your university account for verification.', 
    'Log in with university account to get paid.', 
    'Fill survey with fake personal data to prevent identity theft.', 
    'Close page and report email as login prompts conflict with public surveys.', 
    'Share survey link with classmates to verify.', 
    'Login prompts on external survey links aim to harvest institutional credentials.', 
    'University credential request • Financial incentive lure • Unverified external survey'
),
(
    'صفحة LMS المزيفة', 'Fake Login Page', 
    'رابط يوجهك لصفحة شبيهة بمنصة الجامعة ولكن النطاق في المتصفح هو svu-lms-portal.com.', 
    'إدخال بيانات الدخول المعتادة لأن الواجهة والشعار يطابقان موقع الجامعة.', 
    'حفظ الصفحة في المفضلة لاستخدامها بدلاً من الموقع البطيء.', 
    'إدخال كلمة سر خاطئة عمداً لتجربة الموقع.', 
    'عدم إدخال أي بيانات والإبلاغ عن الرابط والتأكد من نطاق الجامعة الرسمي svuonline.org.', 
    'Option 4', 
    'تغيير النطاق (Domain) هو أساس هجمات انتحال المواقع.', 
    'عنوان URL غير رسمي • نطاق مزيف مشبوه • طلب تسجيل دخول مستعجل',
    'Fake LMS Portal', 'Fake Login Page', 
    'A link redirects you to a page mimicking the university portal, but URL domain is svu-lms-portal.com.', 
    'Enter usual credentials because logo and interface match.', 
    'Bookmark the page for future use.', 
    'Enter a wrong password on purpose to test.', 
    'Do not enter credentials, report link, and verify official domain svuonline.org.', 
    'Domain spoofing is the core indicator of cloned website attacks.', 
    'Unofficial URL • Suspicious domain name • Unsolicited login request'
),
(
    'شبكة Wi-Fi العامة', 'Fake Login Page', 
    'صفحة دخول شبكة عامة في مقهى تطلب تسجيل الدخول باستخدام حساب فيسبوك وكلمة السر المعتادة.', 
    'رفض إدخال كلمة السر الخاصة بحسابك الشخصي واستخدام شبكة البيانات (4G/5G).', 
    'إدخال كلمة سر الفيسبوك لأن شبكات المقاهي تتطلب ذلك عادة.', 
    'إنشاء حساب فيسبوك جديد وهمي والدخول به لتصفح الإنترنت.', 
    'استخدام شبكة Wi-Fi بدون تسجيل الدخول عن طريق تجاوز الصفحة.', 
    'Option 1', 
    'الشبكات العامة المزيفة تستخدم صفحات الدخول لاقتناص كلمات السر.', 
    'طلب كلمة سر الحساب الشخصي • صفحة توثيق غير مشفرة • شبكة مفتوحة غير آمنة',
    'Public Wi-Fi Login', 'Fake Login Page', 
    'A public cafe Wi-Fi captive portal asks you to log in using your Facebook account and main password.', 
    'Refuse entering personal credentials and use mobile data.', 
    'Enter Facebook password as coffee shops usually require it.', 
    'Create a fake Facebook account to gain access.', 
    'Bypass the captive portal without logging in.', 
    'Rogue Wi-Fi access points use captive portals to harvest user credentials.', 
    'Personal account password request • Unencrypted login page • Open untrusted Wi-Fi'
),
(
    'صفحة مستندات أوفيس', 'Fake Login Page', 
    'رابط مشاركة ملف يوجهك لصفحة تطلب تسجيل الدخول ببريدك الإلكتروني لرؤية مستند PDF.', 
    'إدخال البريد وكلمة السر لمشاهدة المستند المهم.', 
    'إغلاق الصفحة فوراً لأن عرض المستندات المباشر لا يتطلب إعادة إدخال كلمة سر البريد.', 
    'تحميل المستند مباشرة دون إدخال كلمة السر.', 
    'طلب إعادة إرسال المستند عبر بريد آخر.', 
    'Option 2', 
    'طلب كلمة سر البريد الإلكتروني للوصول إلى مستند هو أسلوب شائع لسرقة الصلاحيات.', 
    'إعادة طلب كلمة سر البريد • صفحة معاينة مستند غير رسمية • رابط خارجي مبهم',
    'Office Docs Verification', 'Fake Login Page', 
    'A document-sharing link directs to a page demanding your email password to view a PDF file.', 
    'Enter email and password to view document.', 
    'Close page immediately as direct document previews do not require email passwords.', 
    'Download document directly without logging in.', 
    'Ask sender to re-send to another email.', 
    'Prompting for email passwords to view shared documents is a classic credential harvesting attack.', 
    'Email password re-prompt • Fake document preview • Ambiguous external URL'
),
(
    'بوابة الخدمات الحكومية', 'Fake Login Page', 
    'موقع يطلب رقمك الوطني ورمز الحساب البنكي والـ PIN للتحقق من أهليتك للدعم المالي.', 
    'إدخال كافة البيانات المطلوب للحصول على الدعم المستحق.', 
    'إدخال الرقم الوطني فقط وترك الحساب البنكي فارغاً.', 
    'الخروج من الصفحة فوراً لأن المواقع الحكومية لا تطلب رموز البنك السرية (PIN).', 
    'التقاط صورة للشاشة ونشرها في مواقع التواصل للاستفسار عنها.', 
    'Option 3', 
    'المواقع الاحتيالية تستغل اسم الدعم الحكومي لجمع بيانات بنكية وشخصية حساسة.', 
    'طلب رمز الـ PIN البنكي • استغلال الدعم المالي • نموذج إدخال بيانات غير آمن',
    'Government Aid Portal', 'Fake Login Page', 
    'A site requests your National ID, Bank Account Number, and PIN to check financial aid eligibility.', 
    'Enter all required details to receive aid.', 
    'Enter National ID only and leave bank details empty.', 
    'Exit page immediately as official government sites never request bank PINs.', 
    'Screenshot and post on social media to ask.', 
    'Fraudulent sites exploit government aid themes to capture sensitive financial credentials.', 
    'Bank PIN request • Financial subsidy exploitation • Unsecured data collection form'
),
(
    'تفعيل واتساب', 'Fake Login Page', 
    'رسالة تدعي حظر حسابك في واتساب وتطلب منك الضغط على رابط وتأكيد كود التفعيل الرقمي.', 
    'الضغط على الرابط وتزويدهم بالكود لاستعادة الحساب.', 
    'تجاهل الرسالة وتفعيل التحقق بخطوتين (2FA) من داخل التطبيق الرسمي.', 
    'مشاركة الكود مع شخص يدعي أنه من مركز الدعم عبر الواتساب.', 
    'إعادة إرسال كود التفعيل إلى بريد واتساب الرسمي.', 
    'Option 2', 
    'كود التفعيل (OTP) هو مفتاح دخول حسابك، ومشاركته تعطي المهاجم سيطرة كاملة.', 
    'طلب رمز التفعيل (OTP) • تهديد بحظر الحساب • رابط استعادة خارجي',
    'WhatsApp Account Activation', 'Fake Login Page', 
    'A message claims your WhatsApp account is blocked and directs you to a link to submit your OTP activation code.', 
    'Click link and provide code to restore account.', 
    'Ignore message and enable Two-Factor Authentication (2FA) in official app.', 
    'Share code with someone claiming to be WhatsApp support.', 
    'Forward OTP code to WhatsApp email support.', 
    'OTP activation codes grant full account takeover access when shared externally.', 
    'OTP code request • Account suspension threat • External recovery link'
),
(
    'اتصال الدعم الفني', 'IT Support Scam', 
    'اتصال هاتفي يدعي أنه من الدعم الفني للجامعة ويطلب رمز OTP الذي وصلك لتحديث نظامك.', 
    'إعطاء المتصل رمز OTP لمساعدتك في تحديث النظام.', 
    'إنهاء المكالمة فوراً والتواصل مع قسم IT في الجامعة عبر بريدهم الرسمي.', 
    'طلب التحدث مع مدير قسم الدعم الفني عبر نفس المكالمة للتأكد.', 
    'إملاء رمز OTP خطأ للمتصل لمعرفة ردة فعله.', 
    'Option 2', 
    'فريق الدعم الفني الحقيقي لا يطلب رموز OTP أبداً عبر الهاتف.', 
    'انتحال صفة موظف IT • طلب شفاهي لرمز OTP • اتصال هاتفي غير متوقع',
    'IT Support Phone Call', 'IT Support Scam', 
    'A phone call claims to be from university IT support and asks for the OTP sent to your phone to update system.', 
    'Give OTP code to help update system.', 
    'Hang up immediately and contact official university IT email.', 
    'Ask to talk to the IT manager on the same call.', 
    'Read out a fake OTP to see caller reaction.', 
    'Legitimate IT departments never request one-time passwords over phone calls.', 
    'IT staff impersonation • Verbal OTP request • Unexpected phone call'
),
(
    'طلب المدير العاجل', 'IT Support Scam', 
    'رسالة من شخص يدعي أنه مديرك المباشر يطلب تحويل مبلغ مالي مستعجل لسداد صفقة سرية.', 
    'تنفيذ التحويل المالي فوراً لتجنب غضب المدير.', 
    'مراسلة المدير بنفس البريد للسؤال عن تفاصيل الفاتورة.', 
    'إعادة إرسال الطلب لقسم المحاسبة لتنفيذ التحويل نيابة عنك.', 
    'التحقق من المدير شخصياً عبر مكالمة هاتفية موثوقة أو لقاء مباشر قبل إجراء أي تحويل.', 
    'Option 4', 
    'هجوم احتيال الرؤساء (CEO Fraud) يعتمد على سلطة المدير لخلق حالة استعجال.', 
    'انتحال شخصية الإدارة العليا • طلب تحويل مالي مستعجل • التكتم وعدم الإفصاح',
    'Urgent Executive Request', 'IT Support Scam', 
    'An email claiming to be your direct manager requests an urgent wire transfer for a secret business deal.', 
    'Execute wire transfer immediately to prevent manager anger.', 
    'Reply to email asking for invoice details.', 
    'Forward request to accounting to execute transfer on your behalf.', 
    'Verify with manager personally via trusted phone call or in-person before transferring.', 
    'CEO Fraud uses executive authority and urgency to bypass financial verification controls.', 
    'Executive impersonation • Urgent wire transfer request • Secrecy demand'
),
(
    'مساعدة زميل الدراسة', 'IT Support Scam', 
    'زميل يطلب منك إعطاءه اسم المستخدم وكلمة السر الخاصة بك ليقوم بتنزيل محتوى المحاضرات لك.', 
    'مشاركته بيانات الدخول لمساعدتك وكونه صديقاً موثوقاً.', 
    'الاعتذار له ومساعدته بتنزيل الملفات بنفسك دون إعطائه بيانات حسابك.', 
    'تغيير كلمة السر إلى كلمة مؤقتة وإعطائه إياها ثم تغييرها مجدداً.', 
    'إعطاؤه اسم المستخدم فقط بدون كلمة السر.', 
    'Option 2', 
    'حسابك الشخصي يتضمن مسؤولية قانونية وأكاديمية كاملة، ومشاركة الحسابات مجازفة أمنية.', 
    'مشاركة بيانات الاعتماد • استغلال العلاقات الشخصية • تجاوز صلاحيات الحساب',
    'Classmate Assistance Lure', 'IT Support Scam', 
    'A classmate asks for your username and password to download lecture materials for you.', 
    'Share login details as classmate is trusted.', 
    'Politely decline and download files yourself without sharing account details.', 
    'Change password to temporary one, share it, then change back.', 
    'Share username only without password.', 
    'Personal accounts hold full legal responsibility and sharing credentials violates security policies.', 
    'Credential sharing request • Exploitation of trust • Account privilege abuse'
),
(
    'تأكيد شحنة الطرد', 'IT Support Scam', 
    'رسالة SMS تشير لوصول طرد لك وتطلب دفع 1$ لتأكيد العنوان عبر رابط مرفق.', 
    'الضغط على الرابط ودفع المبلغ البسيط لاستلام الطرد.', 
    'الرد على الرسالة النصية بكلمة "تأكيد" لمعرفة التفاصيل.', 
    'تجاهل الرسالة كلياً خاصة إن لم تكن تنتظر شحنة بالفعل، والتحقق عبر موقع شركة الشحن الرسمي.', 
    'الاتصال بالرقم المرفق في الرسالة النصية فوراً.', 
    'Option 3', 
    'هجمات التصيد النصي (Smishing) بالمبالغ البسيطة تُستخدم لسحب بيانات البطاقات البنكية كاملة.', 
    'رسالة نصية احتيالية (Smishing) • رابط دفع مبلغ ضئيل • الادعاء بتأكيد شحنة',
    'Parcel Delivery Confirmation', 'IT Support Scam', 
    'An SMS claims a package arrived and demands a 1 dollar fee via an attached link to confirm address.', 
    'Click link and pay small fee to receive package.', 
    'Reply to SMS with CONFIRM to get details.', 
    'Ignore message if not expecting a package, and verify on official carrier site.', 
    'Call the number attached in the SMS immediately.', 
    'Smishing scams use nominal fee requests to lure victims into entering full banking details.', 
    'Text phishing message (Smishing) • Nominal payment lure • Delivery confirmation claim'
),
(
    'برنامج فحص الجهاز', 'IT Support Scam', 
    'شخص يدعي أنه أخصائي أمن معلومات يطلب منك تثبيت برنامج AnyDesk لتنظيف جهازك من الفيروسات.', 
    'رفض الطلب والإبلاغ عن الحادثة لمدير النظام أو القسم الأمني.', 
    'تثبيت البرنامج ومراقبة ما يفعله على الشاشة.', 
    'تثبيت البرنامج وإغلاق الإنترنت فوراً.', 
    'طلب حظر الحساب الخاص بهذا الشخص عبر وسائل التواصل.', 
    'Option 1', 
    'برامج التحكم عن بعد (Remote Access Trojans) تمنح المهاجم صلاحيات كاملة للوصول إلى جهازك.', 
    'طلب تثبيت برنامج تحكم عن بعد (AnyDesk) • ادعاء الإصابة بفيروسات • جهة غير رسمية',
    'Remote Device Inspection', 'IT Support Scam', 
    'Someone claiming to be a cybersecurity specialist asks you to install AnyDesk to clean viruses on your PC.', 
    'Refuse request and report incident to system administrator.', 
    'Install software and watch onscreen actions.', 
    'Install software and disconnect internet immediately.', 
    'Request social media block for caller account.', 
    'Remote desktop tools allow untrusted third parties full control and access to internal devices.', 
    'Remote software installation request • Fake virus infection warning • Unverified entity'
),
(
    'فلاشة الامتحانات', 'USB Baiting', 
    'وحدة ذاكرة USB ملقاة في قاعة المحاضرات كُتب عليها "أسئلة الامتحانات النهائية 2026".', 
    'توصيلها بالجهاز لمعرفة ما تحتويه ثم مسح الملفات.', 
    'فحص الفلاشة على جهاز صديقك أولاً لحماية جهازك.', 
    'تسليمها لإدارة الكلية أو أمن المبنى دون توصيلها بأي جهاز.', 
    'توصيلها بجهازك بعد إيقاف تشغيل برنامج الحماية.', 
    'Option 3', 
    'هجوم الطُعم يستغل الفضول. الفلاشات الملغومة قد تحتوى على برمجيات تشغيل تلقائي تضر بالنظام.', 
    'وحدة ذاكرة مجهولة (USB Bait) • عنوان مثير للفضول • خطر التشغيل التلقائي',
    'Exam Papers USB Lure', 'USB Baiting', 
    'A flash drive found in a lecture hall is labeled Final Exam Questions 2026.', 
    'Plug into computer to check content then delete.', 
    'Test flash drive on another computer first.', 
    'Hand it over to college admin or campus security without plugging in.', 
    'Plug into device after disabling antivirus.', 
    'USB baiting relies on curiosity to trigger automatic malware execution upon connection.', 
    'Unknown USB media • Curiosity-inducing label • AutoRun malware risk'
),
(
    'قرص صلب خارجي', 'USB Baiting', 
    'قرص صلب مفقود في الكافتيريا يحتوي على ملصق "سجلات الرواتب - سرّي".', 
    'توصيله بالكمبيوتر للبحث عن اسم صاحب القرص وإعادته له.', 
    'عدم توصيله نهائياً وتسليمه لمركز المفقودات.', 
    'فرمتة القرص الصلب فوراً لاستخدامه شخصياً.', 
    'توصيله بشاشة تلفاز بدلاً من الكمبيوتر لرؤية الملفات بأمان.', 
    'Option 2', 
    'محاولة استكشاف الأجهزة المجهولة قد تؤدي لتنفيذ برمجيات خبيثة على مستوى العتاد.', 
    'جهاز تخزين مفقود ومثير للشك • ملصق يدعي سرية البيانات • مخاطر اختراق العتاد',
    'Lost External Hard Drive', 'USB Baiting', 
    'A hard drive found in the cafeteria has a label Payroll Records Confidential.', 
    'Connect to computer to identify owner and return it.', 
    'Do not connect and submit to lost and found desk.', 
    'Format hard drive immediately for personal use.', 
    'Connect to a TV screen instead of PC to view safely.', 
    'Attempting to inspect lost drives can execute firmware-level or auto-run payload attacks.', 
    'Lost physical storage device • Confidentiality lure label • Hardware exploit risk'
),
(
    'التلصص عبر الكتف', 'USB Baiting', 
    'لاحظت شخصاً يقف قريباً جداً منك ويركز بوضوح في شاشتك أثناء كتابتك لكلمة مرور البنك.', 
    'متابعة الكتابة بسرعة عالية حتى لا يلاحظ الحروف.', 
    'تغيير كلمة المرور فوراً بعد مغادرة المكان.', 
    'تغطية لوحة المفاتيح/الشاشة أو التوقف عن الكتابة حتى يبتعد الشخص.', 
    'متابعة الكتابة مع إدخال أرقام خاطئة ومسحها.', 
    'Option 3', 
    'هجمات التلصص تعتمد على الملاحظة المباشرة. حماية الشاشة واللوحة في الأماكن العامة هو الخط الدفاعي الأول.', 
    'مراقبة مباشرة متطفلة • إدخال بيانات حساسة بمكان عام • اختراق الأمان الفيزيائي',
    'Shoulder Surfing Observation', 'USB Baiting', 
    'You notice someone standing closely, staring at your screen while you type your banking password.', 
    'Type quickly so they cannot catch characters.', 
    'Change password immediately after leaving.', 
    'Cover keyboard or screen or stop typing until the person leaves.', 
    'Type wrong numbers on purpose then backspace.', 
    'Shoulder surfing relies on direct visual observation to steal passwords in open environments.', 
    'Intrusive visual observation • Typing credentials in public • Physical security breach'
),
(
    'فتح الباب للغرباء', 'USB Baiting', 
    'شخص يحمل كراتين ثقيلة يطلب منك استخدام بطاقتك الإلكترونية لفتح باب السيرفرات المغلق له.', 
    'فتح الباب له بداعي المساعدة واللطف الإنساني.', 
    'تجاهله وترك الباب مفتوحاً بعد دخولك.', 
    'الاعتذار منه بصلابة وتوجيهه لمكتب الاستقبال/الأمن للتحقق من هويته ورخصته.', 
    'أخذ الأغراض منه وفتح الباب بنفسك ثم إعادتها له.', 
    'Option 3', 
    'هجوم التعقب يستغل التعاطف والمساعدة للالتفاف على إجراءات الأمن الفيزيائي للغرف الحساسة.', 
    'هجوم التسلل الفيزيائي (Tailgating) • استغلال اللطف الإنساني • التجاوز غير المصرح للمنطقة المغلقة',
    'Piggybacking Entry Lure', 'USB Baiting', 
    'A person carrying heavy boxes asks you to badge them into the locked server room.', 
    'Badge them in out of courtesy and help.', 
    'Ignore them and leave the door propped open.', 
    'Politely refuse and direct them to reception or security for verification.', 
    'Take boxes, badge in yourself, then return boxes inside.', 
    'Tailgating exploits human kindness to bypass physical access control systems to restricted zones.', 
    'Physical tailgating attack • Social courtesy exploitation • Unauthorized restricted zone access'
),
(
    'رمز QR ملغوم', 'USB Baiting', 
    'ملصق في الحرم الجامعي يدعوك لمسح رمز QR للحصول على قسيمة شرائية مجانية للقهوة.', 
    'تجنب مسح رموز QR مجهولة المصدر والتأكد من الجهة الراعية.', 
    'مسح الرمز بالهاتف وتتبع الرابط لرؤية ما سيحدث.', 
    'إرسال صورة الرمز لأصدقائك لمسحه أولاً.', 
    'مسح الرمز باستخدام كاميرا الهاتف بدلاً من تطبيق متخصص.', 
    'Option 1', 
    'هجمات القارئ الرقمي (Quishing) تستخدم رموز QR لتوجيه المستخدم لم مواقع تصيد دون معرفة الـ URL المسبق.', 
    'رمز QR مجهول في مكان عام • إغراء بقسائم مجانية • هجوم التصيد السريع (Quishing)',
    'Malicious QR Code Poster', 'USB Baiting', 
    'A campus poster asks you to scan a QR code for a free coffee voucher.', 
    'Avoid scanning untrusted QR codes and verify campaign sponsor.', 
    'Scan code and open link to test.', 
    'Send image of QR code to friends to scan.', 
    'Scan with native camera app instead of dedicated scanner.', 
    'Quishing attacks hide malicious URLs behind physical QR codes to redirect victims to phishing pages.', 
    'Unverified public QR code • Free voucher lure • Malicious QR redirection (Quishing)'
);

-- 5. CREATE TABLE ScamAlerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    title_en TEXT NOT NULL,
    description_en TEXT NOT NULL
);

-- 6. INSERT INTO ScamAlerts (title, description, title_en, description_en) VALUES 
(
    'تنبيه بريد بنكي مزيف', 
    'رسائل تصيد تدعي الحاجة العاجلة لتأكيد بيانات الحساب البنكي.', 
    'Fake Bank Verification Email', 
    'Phishing emails claiming urgent account verification'
),
(
    'احتيال شحنات التوصيل SMS', 
    'رسائل نصية تحاكي شركات الشحن لسرقة بيانات البطاقات.', 
    'Fake Delivery SMS', 
    'Scammers impersonating delivery services'
),
(
    'احتيال حسابات إنستغرام', 
    'رسائل وهمية تهدد بحذف الحساب لاختراق بيانات الدخول.', 
    'Instagram Account Scam', 
    'Fake messages threatening account deletion'
),
(
    'عروض توظيف وهمية', 
    'إعلانات وظائف برواتب خيالية تهدف لجمع البيانات الشخصية والبنكية.', 
    'Fake Job Offer Scam', 
    'Job ads promising high salaries to collect personal and bank data'
),
(
    'احتيال مكافآت واستبيانات', 
    'روابط تستغل أسماء براندات معروفة لتقديم جوائز مقابل طلب اعتماد الحساب.', 
    'Reward Survey Scam', 
    'Links spoofing famous brands promising rewards to harvest credentials'
),
(
    'تحذير أمني مزيف للمتصفح', 
    'نوافذ منبثقة تدعي إصابة الجهاز بالفيروسات للضغط على روابط خبيثة.', 
    'Fake Security Warning Pop-up', 
    'Pop-ups claiming device virus infection to trick users into downloading malware'
),
(
    'سرقة حسابات الواتساب', 
    'رسائل نصية تطلب رمز التفعيل (OTP) لإعادة تفعيل الحساب.', 
    'WhatsApp Account Takeover', 
    'Text messages requesting OTP activation codes to hijack accounts'
),
(
    'صفحة الدخول للخدمات الحكومية', 
    'مواقع غير رسمية تدعي تقديم دعم مالي للحصول على أرقام البطاقات.', 
    'Fake Government Aid Portal', 
    'Unofficial websites claiming financial support to steal banking details'
),
(
    'شبكات Wi-Fi مفتوحة خبيثة', 
    'نقاط اتصال مزيفة في الأماكن العامة لاقتناص كلمات السر والبيانات الشخصية.', 
    'Rogue Public Wi-Fi Portal', 
    'Fake access points in public spots designed to capture login credentials'
);